### PR TITLE
adds play_media service

### PR DESCRIPTION
**Pull request by dgomes**
This adds a play_media service similar to the one found in other media players

this is very helpful to create scripts that change channels

here is an example from mediaroom:

https://www.home-assistant.io/components/media_player.mediaroom#example-press_button-script

### CODE REVIEW

**Comment by dgomes** [comment]
No comments 😞  ?

**Comment by dgomes** [comment]
I need some ❤️

**Comment by JPM-git** [comment]
Is this part of the  Mediaroom component on HA or is there a new .ini file with all the configuration for the Broadlink controler?

**Comment by dgomes** [comment]
This works for ALL media_players components :)

It's just the implementation of the play_media service (can be used in your scripts)

**Comment by dgomes** [comment]
:man_shrugging:

**Pull request closed without merging**
