### PR TITLE
Added  Swing mode

### PR DESCRIPTION
**Pull request by Thunderbird2086**
This change doesn't break existing IR codes.
* command naming
```
# with swing mode
<fan mode>_<swing mode>_<temperature>

# without swing mode or swing mode 'off'
<fan mode>_<temperature>
```
* Added climate IR signals for two models: only cooling mode for now
  1. Daikin ARC478A19
  1. Mitsubishi MSZ J229W

### CODE REVIEW

**Comment by earth08** [comment]
how to use this swing modes on my mitsubishi heavy and ogeneral(fujitsu)
Please guide

**Comment by Thunderbird2086** [comment]
You need to capture IR signals for your air conditioner unless my added one works for you. 
You can find README.md from [my PR](https://github.com/vpnmaster/homeassistant-custom-components/pull/67/files#diff-04c6e90faac2675aa89e2176d2eec7d8R47) or [my repo](https://github.com/Thunderbird2086/homeassistant-custom-components/tree/swing)

**Comment by earth08** [comment]
if your thumsup means correct ,
than its going to be lengthy process foe me

**Comment by Thunderbird2086** [comment]
Sadly, yes.

I did for my Daikin and Mitsubishi’s IR signals which are approximately 1400 and 350

**Comment by earth08** [comment]
true
what does this means
low_mediumlow_31 = 
low_swing_18 = 

how to write codes like,
xxxxxx_xxxxxx_18
temp _swingstyle_temp.
is this the way to write codes?

**Comment by Thunderbird2086** [comment]
Yes, that’s correct.
I didn’t want to break existing code.
‘’’
<fan mode>_<swing mode>_<temperature>
‘’’

**Comment by earth08** [comment]
I have done same thing as per u suggested
like i have
[cool]
auto_swing_18 for swingon
auto_off_18 for swingoff
i am not getting it to work and i am getting error
as
2018-08-10 19:45:46 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall climate.set_temperature (c:7bdef47f584f4776b3bd34210c877390): temperature=22.0, entity_id=['climate.ogen_ground']>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/configparser.py", line 1135, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'false'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/core.py", line 1115, in _event_to_service_call
    await service_handler.func(service_call)
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/climate/__init__.py", line 339, in async_temperature_set_service
    await climate.async_set_temperature(**kwargs)
  File "/usr/local/lib/python3.6/asyncio/futures.py", line 331, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 244, in _wakeup
    future.result()
  File "/usr/local/lib/python3.6/asyncio/futures.py", line 244, in result
    raise self._exception
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/climate/broadlink.py", line 335, in set_temperature
    self.send_ir()
  File "/home/homeassistant/.homeassistant/custom_components/climate/broadlink.py", line 211, in send_ir
    command = self._commands_ini.get(section, value)
  File "/usr/local/lib/python3.6/configparser.py", line 778, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.6/configparser.py", line 1138, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'false'.

please check and let me know if i am doing anything wrong

**Comment by Thunderbird2086** [comment]
The value of `section` was `false`, which is supposed to be `cool` in your case, and my gut feeling says it's something related to configuration or status stored in hass. 

I think it's better if we start checking from configuration, and here is my configuration for Mitsubishi a/c.  
```
- platform: broadlink                                                                  
  name: Mitsubishi                                                                     
  host: xxx.xxx.xxx.xxx                                                                  
  mac: 'xx:xx:xx:xx:xx:xx'                                                             
  ircodes_ini: 'broadlink_ir_codes/broadlink_climate_codes/mitsubishi_msz_j229_w.ini'  
  min_temp: 18                                                                         
  max_temp: 30                                                                         
  target_temp: 24                                                                      
  target_temp_step: 1                                                                  
  default_operation: 'off'                                                             
  default_fan_mode: medium                                                             
  default_swing_mode: swing                                                            
  customize:                                                                           
    operations:                                                                        
      - 'off'                                                                          
      - idle                                                                           
      - cool                                                                           
    fan_modes:                                                                         
      - auto                                                                           
      - low                                                                            
      - medium                                                                         
      - high                       
     #  To make sure changes for swing mode doesn't break existing IR codes,
     #  please comment out
     #  ---- from here                                                     
    swing_modes:                                                                       
      - auto                                                                           
      - swing                                                                          
      - high                                                                           
      - mediumHigh                                                                     
      - mediumLow                                                                      
      - low
      # --- end here                                                                            
```

**Comment by Thunderbird2086** [comment]
I think you didn't put '(quotation mark) to **off**  for your swing modes.   HA interprets `off` without quotation  marks to `false`.   Please take a look at `operations` in my configuration.

**Comment by Thunderbird2086** [comment]
The value of `section` was `false`, which is supposed to be something else such as `cool`, `off`, or `idle`.

I think you didn't put '(quotation mark) to **off**  for your operations (or swing modes).   HA interprets `off` without quotation  marks to `false`.   Please take a look at `operations` in my configuration below. 
```
- platform: broadlink                                                                  
  name: Mitsubishi                                                                     
  host: xxx.xxx.xxx.xxx                                                                  
  mac: 'xx:xx:xx:xx:xx:xx'                                                             
  ircodes_ini: 'broadlink_ir_codes/broadlink_climate_codes/mitsubishi_msz_j229_w.ini'  
  min_temp: 18                                                                         
  max_temp: 30                                                                         
  target_temp: 24                                                                      
  target_temp_step: 1                                                                  
  default_operation: 'off'                                                             
  default_fan_mode: medium                                                             
  default_swing_mode: swing                                                            
  customize:                                                                           
    operations:                                                                        
      - 'off'                                                                          
      - idle                                                                           
      - cool                                                                           
    fan_modes:                                                                         
      - auto                                                                           
      - low                                                                            
      - medium                                                                         
      - high                       
    #  To make sure changes for swing mode doesn't break existing IR codes,
    #  please comment out
    #  ---- from here                                                     
    swing_modes:                                                                       
      - auto                                                                           
      - swing                                                                          
      - high                                                                           
      - mediumHigh                                                                     
      - mediumLow                                                                      
      - low
     # --- end here                                                                            
```

**Comment by earth08** [comment]
Dear,
Thanks for your guidance.
When i tried to swing it does work,
but when i tried to pu swing off and all process on, swing was still on.
here are my climate config:
   - platform: broadlink
    name: oGen Ground
    host: xxx.xxx.xxx.xxx
    mac: 'xx-xx-xx-xx-xx'
    ircodes_ini: 'broadlink_climate_codes/fujitsu.ini'
    min_temp: 18
    max_temp: 30
    target_temp: 24
    target_temp_step: 1
    temp_sensor: sensor.temperature_158d0001f52edb
    default_operation: 'off'
    default_fan_mode: auto
    default_swing_mode: 'off'
    customize:
      operations:
        - 'off'
        - 'on'
        - auto
        - cool
        - dry
        - fan
#        - powerful
#        - sleep
      fan_modes:
        - auto
        - high
        - med
        - low
        - quiet
#  To make sure changes for swing mode doesn't break existing IR codes,
#  please comment out
#  ---- from here                                                     
      swing_modes:
        - 'off'
        - swing
#  --- end here

**Comment by earth08** [comment]
Dear,
i have one request for this,
when applying your broadlink.py and using swing_modes:
and when we try to use codes with swing, it breaks, it doesnt work.
can you add something like if/than commands, or any swingmode like 'off' than in select from the codes available normally from vassillis and yours climate codes?
this will be better and easiest way to imply your file which also works with normal codes.

**Comment by Thunderbird2086** [comment]
@earth08 
In your configuration, I see you're using `fujitsu.ini` which doesn't have code for `swing mode`. 😉 
That's why you got an error of missing key `'high_auto_24' in section: 'cool'`

**Comment by earth08** [comment]
Dear,
thanks for updating code,
i will check it later once i am at home.
i would like to suggest you to give options like
if there in no/off mode selected for swing_mode, than the codes should select for what we have like 
fanmode_temperature
like if there is no code available under cool : fanmode_swingmode_tempereature, than it should consider fonmode_temperature putting swing off.

for me in Fujitsu,
I have many swing options like
off, updown, leftright, and full swing,
+ another butoon for selecting updown at whatever position
+ another button for selecting leftright to whatever posisiton
attaching pic

**Comment by earth08** [comment]
after using your new added file
i got this error when selecting
cool 
auto_off_24
even when i have code

auto_off_24 = JgAGAWo3DQ0NDwwqDAoRKgwODA4ODQsrDCkMDg4ODQ8NKAwpDQ4NDgwODQ8MDwwOCxAMDg0ODg0MEAwODA8MKA4ODBAMDg0NDQ8LDg4NDigNDQ4ODA8NDg0nDikNKA0qCyoLKQ4pDCkODgwODikNDQwPDA8MDwsPDQ8LDw0MDygKLA0NCxAMEAwNDw4MDQ4NDSkNKQ0NDSgNDw0ODA8MDw0NDQ8LDg0PDQ0NDwsQCw8ODA0ODA8MDw0MDg8MDg0NDQ4NDg4NDQ4NDQ0ODQ0ODg0ODA8NDQ0ODg4LDwwPDgwNEAsPCxAMDA8ODA8LDw0ODCkNDwwOCyoNKQ4oDSkNCw8ODSkOEQsADQUAAA==


Sun Aug 12 2018 11:55:19 GMT+0530 (IST)

Error executing service <ServiceCall climate.set_swing_mode (c:51988fd658764e00affe1193382e083c): swing_mode=off, entity_id=['climate.ogen_ground']>

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/configparser.py", line 786, in get
    value = d[option]
  File "/usr/local/lib/python3.6/collections/__init__.py", line 882, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/local/lib/python3.6/collections/__init__.py", line 874, in __missing__
    raise KeyError(key)
KeyError: 'auto_24'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/core.py", line 1115, in _event_to_service_call
    await service_handler.func(service_call)
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/climate/__init__.py", line 420, in async_swing_set_service
    await climate.async_set_swing_mode(swing_mode)
  File "/usr/local/lib/python3.6/asyncio/futures.py", line 331, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 244, in _wakeup
    future.result()
  File "/usr/local/lib/python3.6/asyncio/futures.py", line 244, in result
    raise self._exception
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/climate/broadlink.py", line 365, in set_swing_mode
    self.send_ir()
  File "/home/homeassistant/.homeassistant/custom_components/climate/broadlink.py", line 215, in send_ir
    command = self._commands_ini.get(section, value)
  File "/usr/local/lib/python3.6/configparser.py", line 789, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'auto_24' in section: 'cool'

**Comment by Thunderbird2086** [comment]
@earth08 
Actually I faced very similar issue as you pointed out while working on `dry` mode.
My Daikin a/c supports only `auto swing` for `dry` mode, and I came up with similar idea to yours. 
We will see.   

By the way, I am guessing that you are going to add swing mode to existing `fujitsu.ini`.  My last change supports `off` for swing mode to use `<fan mode>_<temperature>`.

**Comment by earth08** [comment]
Dear even on selecting swingmode off ,
Dear,
I am on newer version,
Ac swings.
I have double checked my codes by regenerating codes again.

**Comment by Thunderbird2086** [comment]
@earth08 
Can you test [my new code](https://github.com/Thunderbird2086/homeassistant-custom-components/blob/swing-mode-off/custom_components/climate/broadlink.py)?

I see discrepancy between actual swing mode and UI  when we change unsupported `swing mode`.
But, the code will not throw an exception.

**Comment by earth08** [comment]
Please check my updated codes,
i have updated it for first time,
Please correct it if there is any mistake

**Comment by earth08** [comment]
This is the error when i tried to use cool high_swing_24
2018-08-15 12:20:38 ERROR (SyncWorker_12) [custom_components.climate.broadlink] section=(cool), value=(high_swing_24)

**Comment by Thunderbird2086** [comment]
Apologies!
Mistakenly pushed test code which not sending IR signals

**Comment by earth08** [comment]
With the latest code on

https://github.com/Thunderbird2086/homeassistant-custom-components/blob/swing-mode-off/custom_components/climate/broadlink.py

My AC config in UI lost,
There is nothing in UI for my ac

**Comment by Thunderbird2086** [comment]
@earth08 If your ac didn't show up on UI, then it probably failed to initialize. 
Let me take a look at it.

**Comment by earth08** [comment]
@Thunderbird2086 
I tried with you new code, ui shows my ac,
but swing still doesnt work as expected, when i select off it start swinging and when i select swing it stops swinging.

**Comment by Thunderbird2086** [comment]
@earth08 
That's very weird.  I confirmed it picked up correct IR codes(at least keys)
which swing mode was on your UI when it stopped?

**Comment by Thunderbird2086** [comment]
If you turn **debug** on for `custom_components.climate.broadlink` and restart HA, then you will see a key when you change operation and/or swing mode something like:
```
2018-08-17 19:45:22 DEBUG (SyncWorker_3) [custom_components.climate.broadlink] section=(fan), value=(quiet_24)
2018-08-17 19:45:27 DEBUG (SyncWorker_0) [custom_components.climate.broadlink] value=(quiet_24)
2018-08-17 19:45:27 DEBUG (SyncWorker_0) [custom_components.climate.broadlink] value=(quiet_24)
2018-08-17 19:45:27 DEBUG (SyncWorker_0) [custom_components.climate.broadlink] section=(cool), value=(quiet_24)
2018-08-17 19:45:32 DEBUG (SyncWorker_1) [custom_components.climate.broadlink] value=(quiet_swing_24)
2018-08-17 19:45:32 DEBUG (SyncWorker_1) [custom_components.climate.broadlink] value=(quiet_swing_24)
2018-08-17 19:45:32 DEBUG (SyncWorker_1) [custom_components.climate.broadlink] section=(cool), value=(quiet_swing_24)
```
Check which key your HA dumps.

**Comment by Thunderbird2086** [comment]
I pushed new code with three lines for debug log, @earth08

**Comment by Thunderbird2086** [comment]
@earth08 
I have realized that it's not a right direction, which we have tried to add swing mode to existing not-having-swing mode IR-signals configurations.  It increases code complexity which is about to compromise user's mistake on configuration.  That's why I added my own mitsubishi IR signals even though @vpnmaster provided it without swing mode which still works for me. 

Sorry to say this, but I am going to roll back changes after [f259e44
](https://github.com/vpnmaster/homeassistant-custom-components/pull/67/commits/f259e4486ec90894c3ff6e11dd119f78dff81e7e), but keep it under `swing-mode-off` branch.

**Comment by earth08** [comment]
Please check and allow the file for  oGeneral AC submitted by submitted by me.

**Comment by Thunderbird2086** [comment]
closed this PR as I started working on adding new [feature](
https://github.com/Thunderbird2086/homeassistant-custom-components/tree/feature/added-custom-settings-to-operations)

**Pull request closed without merging**
