### PR TITLE
allow media_player to be always on

### PR DESCRIPTION
**Pull request by abmantis**
Since the TV can be turned on with the real remote, the component would be de-synchronized. So, it the component was in the "off" state and the TV was already on, there would be no way to do anything since the buttons would be disabled on the UI. Trying to turn the UI on, would turn the TV off :-D

### CODE REVIEW

**Comment by vpnmaster** [comment]
Most tv's have separate codes for off and on commands. You can find them on the net.
So if your tv is on and you turn it off from the remote control, when you turn off the component from the UI does nothing.
Also. there is an undocumented ping service for tv's with lan support but not official API, so the component can determine if your tv is on or off (ping_host: 192.168.10.72).

**Comment by abmantis** [comment]
I couldn't find different codes for mine. Also, it's a dumb TV, no ethernet or wifi. 
The parameter I added is configurable anyway, and defaults to False, so it does not break the current usage of the component.

**Comment by abmantis** [comment]
No merge then?

**Comment by vpnmaster** [comment]
Sorry. I had some conflicts. I'll add your changes very soon.

**Pull request closed without merging**
